### ISSUE TITLE
Image Scaling Quality is Very Low

### ISSUE THREAD

**Issue by CenturySparkle** [buchizo/ClaudiaIDE#173] opened 2023-12-08 17:48 UTC
Since the last release, image scaling quality is very low.  Images now have jagged edges, black lines especially.  The scaling quality was excellent for years until this last release.

**Comment by buchizo** [comment] 2023-12-08 20:47
@CenturySparkle I guess that issue was resolved by greater than version 3.1.24

**Comment by stricq** [comment] 2023-12-20 03:34
I'm on 3.1.26 and the scaling is pretty bad.  Jaggies and blocks everywhere.

**Comment by buchizo** [comment] 2023-12-20 03:39
@stricq @CenturySparkle 
Please could you provide more details such as options, screen shot, e.t.c.. ?

**Comment by stricq** [comment] 2023-12-21 21:45
![ClaudIDE 3 1 19](https://github.com/buchizo/ClaudiaIDE/assets/1395862/b095e7d4-0d4c-4ec7-84ac-9e46c73dc1a0) ![ClaudIDE 3 1 26](https://github.com/buchizo/ClaudiaIDE/assets/1395862/86068ad7-e499-4a53-8ba6-0afc0294d102)

The first image is from v3.1.19 and the second is from 3.1.26.  You can clearly see the lack of quality in the scaling from the two versions.

**Comment by buchizo** [comment] 2023-12-22 17:02
@stricq 
In my environment, unfortunately jaggies did not reproduce. Could you provide more info? for example, your image, your ClaudiaIDE options (image strech, soft edge size, and others).

**Comment by stricq** [comment] 2023-12-23 07:30
![image](https://github.com/buchizo/ClaudiaIDE/assets/1395862/471c9aef-423a-4a76-898c-a26adb8f02c8)

**Comment by buchizo** [comment] 2023-12-23 16:15
Ok, I understood it. If background image original size is bigger than text editor area size, this issue occurred. That means is downscale has problem. If background image is smaller than text editor, it's no problem. This issue's root cause is VisualBrush, maybe. I try fix it.

**Comment by buchizo** [comment] 2023-12-23 18:16
I fixed this issue by version 3.1.28.

**Comment by stricq** [comment] 2023-12-24 03:09
Confirmed working with 3.1.28.  Thanks for looking into this.

**Closed** 2023-12-24 16:28 UTC
Labels: bug
